CREATE DATABASE IF NOT EXISTS hall_of_faces;

use hall_of_faces

CREATE TABLE IF NOT EXISTS people (
	id VARCHAR(36) NOT NULL PRIMARY KEY,
	category VARCHAR(50),
	name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS images (
	id VARCHAR(36) NOT NULL,
	path VARCHAR(500),
	encoding BLOB DEFAULT NULL,
	PRIMARY KEY (id, path),
	FOREIGN KEY (id) REFERENCES people(id)
);
